import type { Metadata } from "next";
import "./globals.css";
import "@livekit/components-styles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://unpkg.com/98.css" />
      </head>
      <body className="antialiased" style={{ fontFamily: "'Minecraft Standard', 'Minecraft', monospace" }}>
        {children}
      </body>
    </html>
  );
}
